services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: mwengenharia
      POSTGRES_USER: mw
      POSTGRES_PASSWORD: mw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  s3mock:
    image: adobe/s3mock:5.2.2
    environment:
      COM_ADOBE_TESTING_S3MOCK_STORE_INITIAL_BUCKETS: mwengenharia
      COM_ADOBE_TESTING_S3MOCK_STORE_ROOT: /s3mockroot
      COM_ADOBE_TESTING_S3MOCK_STORE_RETAIN_FILES_ON_EXIT: "true"
    ports:
      - "9000:9090"
    volumes:
      - s3mock_data:/s3mockroot

volumes:
  postgres_data:
  s3mock_data:
